site_name: WorkspacesIO
site_url: https://workspacesio.subdavis.com
site_description: Documentation for WorkspacesIO
site_author: Brandon Davis

repo_url: https://github.com/subdavis/workspaces-io

theme:
    name: material
    highlightjs: true

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Design: design.md
  - Server Configuration:
    - Administrator Guide: admin/administrator-guide.md
    - S3 guide: admin/s3.md
  - User Guide:
    - Getting Started: user-guide/user-guide.md
